

INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values('The Old Guitarist', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bc/Old_guitarist_chicago.jpg/800px-Old_guitarist_chicago.jpg','Pablo Picasso', '111 S Michigan Ave', 'Art Institute of Chicago','Illinois','60603', 'Chicago', '(312) 443-3600', 'http://www.artic.edu/');
INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values('The Starry Night', 'https://www.moma.org/wp/moma_learning/wp-content/uploads/2012/07/Van-Gogh.-Starry-Night-469x376.jpg','Vincent van Gogh','11 W 53rd St', 'Museum of Modern Art','New York','10019', 'New York', '(212) 708-9400', 'https://www.moma.org/');
INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values("Canto 100 - Saint Bernard's Prayer", 'https://files.dma.org/multimedia/images/81567062008153_thumbnail.jpg', 'Salvador Dali','1717 N Harwood St', 'Dallas Museum of Art','Texas','60603', 'Dallas', '214-922-1200', 'https://dma.org/');
INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values('Guernica', 'http://www.museoreinasofia.es/sites/default/files/obras/DE00050_0.jpg','Pablo Picasso', '52 Calle de Santa Isabel', 'Museo Nacional Centro de Arte Reina Sofía','Spain','28012', 'Madrid', '+34 917 74 10 00', 'http://www.museoreinasofia.es/en');
INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values("Les Demoiselles d'Avignon", 'https://www.moma.org/media/W1siZiIsIjE1MTI3MSJdLFsicCIsImNvbnZlcnQiLCItcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=f7560007ccdf470f','Pablo Picasso', '11 W 53rd St', 'Museum of Modern Art','New York','10019', 'New York', '(212) 708-9400', 'https://www.moma.org/');
INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values('The Weeping Woman', 'https://www.pablopicasso.org/images/paintings/the-weeping-woman.jpg','Pablo Picasso', 'SE1 9TG', 'Tate Modern','London','NA', 'Bankside', '+44 20 7887 8888', 'http://www.tate.org.uk/visit/tate-modern');
INSERT INTO art (art_title, image_url, artist_name, address, museum_name, state, zipcode, city, phone, website)Values('Chicago Picasso', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/2004-09-07_1800x2400_chicago_picasso.jpg/1200px-2004-09-07_1800x2400_chicago_picasso.jpg','Pablo Picasso', '50 W Washington St', 'NA','Illinois','60602', 'Chicago', 'NA', 'NA');
